
DEFAULT:
  GANACHE_URL : 'http://127.0.0.1:8545'
  NETWORK_ID : 1591520511878
  ABI_FILE_PATH : './blockchain/build/contracts'
  ACCOUNT_KEYS_PATH : './blockchain/keys'
  TOTAL_NODES : 10
  ETH_PER_NODE : 100
  MNEMONIC : 'master doll scare pilot clinic will police slim stove secret pink outside' 

DB:
  HOST : 'localhost'
  USER : 'chainrunnermanager'
  PASSWORD : 'shoptikftw'
  DB : 'chainrunner_db'